/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Module__factory } from "./ERC20Module__factory";
export { ERC721Module__factory } from "./ERC721Module__factory";
