/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Signatory,
  SignatoryInterface,
} from "../../../../@doncesarts/tokenbound-contracts/abstract/Signatory";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "magicValue",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Signatory__factory {
  static readonly abi = _abi;
  static createInterface(): SignatoryInterface {
    return new Interface(_abi) as SignatoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Signatory {
    return new Contract(address, _abi, runner) as unknown as Signatory;
  }
}
