/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC6551Executable,
  IERC6551ExecutableInterface,
} from "../../../erc6551/interfaces/IERC6551Executable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint8",
        name: "operation",
        type: "uint8",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IERC6551Executable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC6551ExecutableInterface {
    return new Interface(_abi) as IERC6551ExecutableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC6551Executable {
    return new Contract(address, _abi, runner) as unknown as IERC6551Executable;
  }
}
