/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  PackRegistry,
  PackRegistryInterface,
} from "../../contracts/PackRegistry";

const _abi = [
  {
    inputs: [],
    name: "AccountCreationFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ERC6551AccountCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "account",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "createAccount",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061031f806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063246a00211461003b5780638a54c52f1461006a575b600080fd5b61004e61004936600461029b565b61007d565b6040516001600160a01b03909116815260200160405180910390f35b61004e61007836600461029b565b610107565b6040805160b78082018490526001600160a01b038516609783015260778201869052605782018790526e5af43d82803e903d91602b57fd5bf3603783015260288201889052733d60ad80600a3d3981f3363d3d373d3d3d363d736014830152815260d7810190915280516020909101206000906100fa8682610241565b9150505b95945050505050565b6040805160b78082018490526001600160a01b038516609783015260778201869052605782018790526e5af43d82803e903d91602b57fd5bf3603783015260288201889052733d60ad80600a3d3981f3363d3d373d3d3d363d736014830152815260d781019091526000906000610185878380519060200120610241565b90506001600160a01b0381163b156101a05791506100fe9050565b604080516001600160a01b038381168252602082018a9052918101889052859180881691908b16907f79f19b3655ee38b1ce526556b7731a20c8f218fbda4a3990b6cc4172fdf887229060600160405180910390a4868251602084016000f590506001600160a01b0381166100fa576040517f20188a5900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b600061024e838330610255565b9392505050565b6000604051836040820152846020820152828152600b8101905060ff815360559020949350505050565b80356001600160a01b038116811461029657600080fd5b919050565b600080600080600060a086880312156102b357600080fd5b6102bc8661027f565b945060208601359350604086013592506102d86060870161027f565b94979396509194608001359291505056fea26469706673582212202b87353e1b27aa5efc504b8c4b292ca64257a3f3d016bcf825066d9923439b4d64736f6c63430008140033";

type PackRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PackRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PackRegistry__factory extends ContractFactory {
  constructor(...args: PackRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PackRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PackRegistry__factory {
    return super.connect(runner) as PackRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PackRegistryInterface {
    return new Interface(_abi) as PackRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PackRegistry {
    return new Contract(address, _abi, runner) as unknown as PackRegistry;
  }
}
